language: node_js
node_js: stable
addons:
  firefox: latest
  apt:
      sources:
        - google-chrome
      packages:
        - google-chrome-stable
sudo: required
before_script:
- npm install -g bower eslint eslint-plugin-html web-component-tester
- bower install
- eslint *.html
script:
- xvfb-run wct
